CREATE TABLE [Ingredient] (
	Id varchar(36) NOT NULL,
	WordId varchar(255) NOT NULL,
  CONSTRAINT [PK_INGREDIENT] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [RecipeIngredient] (
	Id varchar(36) NOT NULL,
	RecipeId varchar(36) NOT NULL,
	IngredientId varchar(36) NOT NULL,
  CONSTRAINT [PK_RECIPEINGREDIENT] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Recipe] (
	Id varchar(36) NOT NULL,
	Title varchar(255) NOT NULL,
	HostId varchar(36) NOT NULL,
	Path varchar(255) NOT NULL,
	ImageUrl varchar(255) NOT NULL,
  CONSTRAINT [PK_RECIPE] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Host] (
	Id varchar(36) NOT NULL,
	Name varchar(255) NOT NULL,
	Url varchar(255) NOT NULL,
	LogoUrl varchar(255) NOT NULL,
  CONSTRAINT [PK_HOST] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)


ALTER TABLE [Ingredient] WITH CHECK ADD CONSTRAINT [Ingredient_fk0] FOREIGN KEY ([WordId]) REFERENCES [Word]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Ingredient] CHECK CONSTRAINT [Ingredient_fk0]
GO

ALTER TABLE [RecipeIngredient] WITH CHECK ADD CONSTRAINT [RecipeIngredient_fk0] FOREIGN KEY ([RecipeId]) REFERENCES [Recipe]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [RecipeIngredient] CHECK CONSTRAINT [RecipeIngredient_fk0]
GO
ALTER TABLE [RecipeIngredient] WITH CHECK ADD CONSTRAINT [RecipeIngredient_fk1] FOREIGN KEY ([IngredientId]) REFERENCES [Ingredient]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [RecipeIngredient] CHECK CONSTRAINT [RecipeIngredient_fk1]
GO

ALTER TABLE [Recipe] WITH CHECK ADD CONSTRAINT [Recipe_fk0] FOREIGN KEY ([HostId]) REFERENCES [Host]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Recipe] CHECK CONSTRAINT [Recipe_fk0]
GO

