CREATE TABLE [Ingredient] (
	Id UNIQUEIDENTIFIER,
	Name varchar(255) NOT NULL,
  CONSTRAINT [PK_INGREDIENT] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [RecipeIngredient] (
	Id UNIQUEIDENTIFIER,
	RecipeId UNIQUEIDENTIFIER NOT NULL,
	IngredientId UNIQUEIDENTIFIER NOT NULL,
	DerivedFrom varchar(255) NOT NULL,
  CONSTRAINT [PK_RECIPEINGREDIENT] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Recipe] (
	Id UNIQUEIDENTIFIER,
	Title varchar(255) NOT NULL,
	HostId UNIQUEIDENTIFIER NOT NULL,
	Url varchar(255) NOT NULL,
	ImageUrl varchar(255),
  CONSTRAINT [PK_RECIPE] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Host] (
	Id UNIQUEIDENTIFIER,
	Name varchar(255) NOT NULL,
	Url varchar(255) NOT NULL,
	LogoUrl varchar(255),
  CONSTRAINT [PK_HOST] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)

ALTER TABLE [RecipeIngredient] WITH CHECK ADD CONSTRAINT [RecipeIngredient_fk0] FOREIGN KEY ([RecipeId]) REFERENCES [Recipe]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [RecipeIngredient] CHECK CONSTRAINT [RecipeIngredient_fk0]
GO
ALTER TABLE [RecipeIngredient] WITH CHECK ADD CONSTRAINT [RecipeIngredient_fk1] FOREIGN KEY ([IngredientId]) REFERENCES [Ingredient]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [RecipeIngredient] CHECK CONSTRAINT [RecipeIngredient_fk1]
GO

ALTER TABLE [Recipe] WITH CHECK ADD CONSTRAINT [Recipe_fk0] FOREIGN KEY ([HostId]) REFERENCES [Host]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Recipe] CHECK CONSTRAINT [Recipe_fk0]
GO

