INSERT INTO [Ingredient] ([Id],[Name])
VALUES
('00000000-0000-0000-0000-000000000000','NO INGREDIENTS FOUND'),
(NEWID(),'3-kornsblanding'),
(NEWID(),'5-kornsblanding'),
(NEWID(),'5-kornsflager'),
(NEWID(),'a38'),
(NEWID(),'abrikos i lage'),
(NEWID(),'abrikos'),
(NEWID(),'abrikosmarmelade'),
(NEWID(),'agerhøne'),
(NEWID(),'agurk'),
(NEWID(),'ahornsirup'),
(NEWID(),'ajvar relish'),
(NEWID(),'akaciehonning'),
(NEWID(),'allehånde'),
(NEWID(),'amarenakirsebær'),
(NEWID(),'ananas'),
(NEWID(),'ananasjuice'),
(NEWID(),'ananaskirsebær'),
(NEWID(),'and'),
(NEWID(),'andebouillon'),
(NEWID(),'andebryst'),
(NEWID(),'andefedt'),
(NEWID(),'andelever'),
(NEWID(),'andelår'),
(NEWID(),'anisfrø'),
(NEWID(),'ansjosfilet'),
(NEWID(),'appelsin usprøjtet'),
(NEWID(),'appelsin'),
(NEWID(),'appelsinjuice'),
(NEWID(),'appelsinlikør'),
(NEWID(),'appelsinsaft'),
(NEWID(),'artiskok'),
(NEWID(),'artiskokbund'),
(NEWID(),'artiskokhjerte'),
(NEWID(),'asie'),
(NEWID(),'asketræ'),
(NEWID(),'aspargeskartoffel'),
(NEWID(),'atamon'),
(NEWID(),'aubergine'),
(NEWID(),'avocado'),
(NEWID(),'babysalatblade'),
(NEWID(),'babyspinatblad'),
(NEWID(),'bacon'),
(NEWID(),'bacontern'),
(NEWID(),'bagekartoffel'),
(NEWID(),'bagel'),
(NEWID(),'bagepulver'),
(NEWID(),'balsamico'),
(NEWID(),'bambusskud'),
(NEWID(),'banan'),
(NEWID(),'bananskalotteløg'),
(NEWID(),'barbecuekrydderi'),
(NEWID(),'barbecuesauce'),
(NEWID(),'basilikum'),
(NEWID(),'basilikumblad'),
(NEWID(),'basmatiris'),
(NEWID(),'bataviasalat'),
(NEWID(),'bayersk pølse'),
(NEWID(),'bayonneskinke'),
(NEWID(),'bearnaiseessens'),
(NEWID(),'belgisk vaffel'),
(NEWID(),'belugalinser'),
(NEWID(),'benfri sild'),
(NEWID(),'biscotti'),
(NEWID(),'bladselleri'),
(NEWID(),'blodappelsin'),
(NEWID(),'blomkål'),
(NEWID(),'blomme'),
(NEWID(),'blommeeddike'),
(NEWID(),'blommemarmelade'),
(NEWID(),'blommetomat'),
(NEWID(),'blomster'),
(NEWID(),'blomsterhonning'),
(NEWID(),'blå birkes'),
(NEWID(),'blå vindrue'),
(NEWID(),'blåbær'),
(NEWID(),'blåbærsirup'),
(NEWID(),'blåmusling'),
(NEWID(),'blåskimmelost'),
(NEWID(),'boghvede'),
(NEWID(),'boghvedeflage'),
(NEWID(),'boghvedegryn'),
(NEWID(),'boghvedemel'),
(NEWID(),'bolsjebede'),
(NEWID(),'bresaola'),
(NEWID(),'brie'),
(NEWID(),'broccoli'),
(NEWID(),'broccolini'),
(NEWID(),'brombær'),
(NEWID(),'brun farin'),
(NEWID(),'brune ris'),
(NEWID(),'brunkage'),
(NEWID(),'brændenælde'),
(NEWID(),'brændt figen'),
(NEWID(),'brændt mandel'),
(NEWID(),'brød'),
(NEWID(),'brøndkarse'),
(NEWID(),'bulgur'),
(NEWID(),'burgerbolle'),
(NEWID(),'butter bean'),
(NEWID(),'butterdej'),
(NEWID(),'butternut squash'),
(NEWID(),'byggryn'),
(NEWID(),'bær'),
(NEWID(),'bøftomat'),
(NEWID(),'bøgeblad'),
(NEWID(),'bøgehat'),
(NEWID(),'bønne-mix'),
(NEWID(),'bønner'),
(NEWID(),'bønner i chilisauce'),
(NEWID(),'bønnespire'),
(NEWID(),'cannellinibønner'),
(NEWID(),'cashewnød'),
(NEWID(),'cayennepeber'),
(NEWID(),'champignon'),
(NEWID(),'chateaubriand'),
(NEWID(),'cheddar'),
(NEWID(),'cherrytomat'),
(NEWID(),'chiafrø'),
(NEWID(),'chili'),
(NEWID(),'chilipulver'),
(NEWID(),'chokolade'),
(NEWID(),'chokoladeis'),
(NEWID(),'chokoladekaffebønne'),
(NEWID(),'chorizo'),
(NEWID(),'ciabattabolle'),
(NEWID(),'ciabattabrød'),
(NEWID(),'citron usprøjtet'),
(NEWID(),'citron'),
(NEWID(),'citrongræs'),
(NEWID(),'citronmelisse'),
(NEWID(),'citronmelisseblad'),
(NEWID(),'citronolie'),
(NEWID(),'citronpeber'),
(NEWID(),'citronsaft'),
(NEWID(),'citronsyre'),
(NEWID(),'citrontimian'),
(NEWID(),'citronverbena'),
(NEWID(),'citrusmarmelade'),
(NEWID(),'clementin'),
(NEWID(),'clementinsaft'),
(NEWID(),'cocktailpølse'),
(NEWID(),'cocktailtomat'),
(NEWID(),'coleslaw'),
(NEWID(),'cornflakes'),
(NEWID(),'cornichon'),
(NEWID(),'courgette'),
(NEWID(),'couscousgryn'),
(NEWID(),'coxorange'),
(NEWID(),'cremefraiche'),
(NEWID(),'crouton'),
(NEWID(),'daddel'),
(NEWID(),'danskvand'),
(NEWID(),'delikatessepaprika'),
(NEWID(),'dijonnaise'),
(NEWID(),'dijonsennep'),
(NEWID(),'dild'),
(NEWID(),'dilddressing'),
(NEWID(),'dildfrø'),
(NEWID(),'dildkviste'),
(NEWID(),'drueagurk'),
(NEWID(),'dukkah'),
(NEWID(),'durumbrød'),
(NEWID(),'durummel'),
(NEWID(),'dyrebov'),
(NEWID(),'dyrefilet'),
(NEWID(),'dyrekølle'),
(NEWID(),'dyreryg'),
(NEWID(),'dådyr'),
(NEWID(),'døvnælde'),
(NEWID(),'edamamebønne'),
(NEWID(),'eddike'),
(NEWID(),'edelsüsspaprika'),
(NEWID(),'egeløvsalat'),
(NEWID(),'ekstralagret ost'),
(NEWID(),'emmentaler'),
(NEWID(),'enebær'),
(NEWID(),'engelsk sauce'),
(NEWID(),'enokisvamp'),
(NEWID(),'espressokaffe'),
(NEWID(),'estragon'),
(NEWID(),'estragonblad'),
(NEWID(),'estragoneddike'),
(NEWID(),'estragonkvist'),
(NEWID(),'falaffel'),
(NEWID(),'fasan'),
(NEWID(),'feldsalat'),
(NEWID(),'fennikel'),
(NEWID(),'fennikelfrø'),
(NEWID(),'fersk laks'),
(NEWID(),'fersk spæk'),
(NEWID(),'fersken fra dåse'),
(NEWID(),'fersken'),
(NEWID(),'feta'),
(NEWID(),'figen'),
(NEWID(),'filodej'),
(NEWID(),'filonebrød'),
(NEWID(),'fine ært'),
(NEWID(),'fint salt'),
(NEWID(),'finvalsede havregryn'),
(NEWID(),'fiskebolle'),
(NEWID(),'fiskebouillon'),
(NEWID(),'fiskefars'),
(NEWID(),'fiskefilet'),
(NEWID(),'fiskefond'),
(NEWID(),'fiskefrikadelle'),
(NEWID(),'fiskesauce'),
(NEWID(),'fjæsingfilet'),
(NEWID(),'fladbrød'),
(NEWID(),'flagesalt'),
(NEWID(),'flanksteak'),
(NEWID(),'flormelis'),
(NEWID(),'flute'),
(NEWID(),'flyvefiskerogn'),
(NEWID(),'flået tomat'),
(NEWID(),'flæskesteg'),
(NEWID(),'fløde'),
(NEWID(),'flødeost'),
(NEWID(),'focacciabrød'),
(NEWID(),'forel'),
(NEWID(),'formfranskbrød'),
(NEWID(),'forårsløg'),
(NEWID(),'forårsrulledej'),
(NEWID(),'fraiche'),
(NEWID(),'framboise'),
(NEWID(),'franskbrød'),
(NEWID(),'frillicesalat'),
(NEWID(),'friséesalat'),
(NEWID(),'frisk salvie'),
(NEWID(),'fritureolie'),
(NEWID(),'fromage fraiche'),
(NEWID(),'frosne bær'),
(NEWID(),'frosne hindbær'),
(NEWID(),'frosne røde bær'),
(NEWID(),'frossen ært'),
(NEWID(),'frossent blåbær'),
(NEWID(),'frossent brombær'),
(NEWID(),'frossent jordbær'),
(NEWID(),'frosset skovbær'),
(NEWID(),'frugt'),
(NEWID(),'frugtgrød'),
(NEWID(),'frysetørret bær'),
(NEWID(),'frysetørret hindbær'),
(NEWID(),'fuldkornsbolle'),
(NEWID(),'fuldkornsdurummel'),
(NEWID(),'fuldkornshvedekiks'),
(NEWID(),'fuldkornshvedemel'),
(NEWID(),'fuldkornslasagneplade'),
(NEWID(),'fuldkornsnudler'),
(NEWID(),'fuldkornspasta'),
(NEWID(),'fuldkornspitabrød'),
(NEWID(),'fuldkornspølsebrød'),
(NEWID(),'fuldkornsrugbrød'),
(NEWID(),'fuldkornsspaghetti'),
(NEWID(),'fuldkornsspeltmel'),
(NEWID(),'galiamelon'),
(NEWID(),'garam masala'),
(NEWID(),'ged'),
(NEWID(),'gedekød'),
(NEWID(),'gedeost'),
(NEWID(),'glaskål'),
(NEWID(),'glasnuddel'),
(NEWID(),'glasur'),
(NEWID(),'glukosesirup'),
(NEWID(),'gorgonzola'),
(NEWID(),'gouda'),
(NEWID(),'grahamsmel'),
(NEWID(),'granatæble'),
(NEWID(),'grape'),
(NEWID(),'grapefrugt'),
(NEWID(),'grapefrugtsaft'),
(NEWID(),'gravad laks'),
(NEWID(),'grillkrydderi'),
(NEWID(),'grisekød'),
(NEWID(),'grissini'),
(NEWID(),'groft flute'),
(NEWID(),'groft knækbrød'),
(NEWID(),'groft rugbrød'),
(NEWID(),'groft rugmel'),
(NEWID(),'groft salt'),
(NEWID(),'groft sandwichbrød'),
(NEWID(),'groft toastbrød'),
(NEWID(),'grov bulgur'),
(NEWID(),'grov pizzadej'),
(NEWID(),'grov sandwichbolle'),
(NEWID(),'grov sennep'),
(NEWID(),'grovbolle'),
(NEWID(),'grovbrød'),
(NEWID(),'grovvalsede havregryn'),
(NEWID(),'gråand'),
(NEWID(),'græskar'),
(NEWID(),'græskarkerner'),
(NEWID(),'græskarsuppe'),
(NEWID(),'grødris'),
(NEWID(),'grøn asparges'),
(NEWID(),'grøn bønne'),
(NEWID(),'grøn chilipeber'),
(NEWID(),'grøn kardemommekapsel'),
(NEWID(),'grøn karrypasta'),
(NEWID(),'grøn linse'),
(NEWID(),'grøn oliven'),
(NEWID(),'grøn oliventapenade'),
(NEWID(),'grøn peberfrugt'),
(NEWID(),'grøn peberkorn'),
(NEWID(),'grøn salat'),
(NEWID(),'grøn squash'),
(NEWID(),'grøn tomat'),
(NEWID(),'grøn vindrue'),
(NEWID(),'grøn æble'),
(NEWID(),'grønkål'),
(NEWID(),'grønkålsblad'),
(NEWID(),'grøntsagsbouillon'),
(NEWID(),'grøntsagsfond'),
(NEWID(),'gul bede'),
(NEWID(),'gul peberfrugt'),
(NEWID(),'gul squash'),
(NEWID(),'gulerod'),
(NEWID(),'gulerodssaft'),
(NEWID(),'gurkemeje'),
(NEWID(),'gurkemejerod'),
(NEWID(),'gås'),
(NEWID(),'gåsefedt'),
(NEWID(),'gær'),
(NEWID(),'hakkebøf'),
(NEWID(),'hakkede tomater med chili'),
(NEWID(),'hakkede tomater'),
(NEWID(),'hakket dyrekød'),
(NEWID(),'hakket grønkål'),
(NEWID(),'hakket kalkunkød'),
(NEWID(),'hakket kalvekød'),
(NEWID(),'hakket kyllingekød'),
(NEWID(),'hakket lammekød'),
(NEWID(),'hakket oksekød'),
(NEWID(),'hakket spinat'),
(NEWID(),'hakket svinekød'),
(NEWID(),'hakket torsk'),
(NEWID(),'halloumi'),
(NEWID(),'halvtør hvidvin'),
(NEWID(),'hamburgerryg'),
(NEWID(),'hampefrø'),
(NEWID(),'hare'),
(NEWID(),'haricot vert'),
(NEWID(),'harissa'),
(NEWID(),'hasselnøddeflage'),
(NEWID(),'hasselnøddekerne'),
(NEWID(),'hasselnøddeolie'),
(NEWID(),'havarti'),
(NEWID(),'havbars'),
(NEWID(),'havkat'),
(NEWID(),'havregryn'),
(NEWID(),'havrekiks'),
(NEWID(),'havreklid'),
(NEWID(),'havsalt'),
(NEWID(),'havtaskefilet'),
(NEWID(),'havtaskehale'),
(NEWID(),'havtaskekæbe'),
(NEWID(),'havtorn'),
(NEWID(),'havtornsaft'),
(NEWID(),'havtornsyltetøj'),
(NEWID(),'havørred'),
(NEWID(),'hedvin'),
(NEWID(),'hel spidskommen'),
(NEWID(),'helbladet spinat'),
(NEWID(),'hellefisk'),
(NEWID(),'helleflynder'),
(NEWID(),'helt hvidløg'),
(NEWID(),'herbes de provence'),
(NEWID(),'hindbær'),
(NEWID(),'hindbærmarmelade'),
(NEWID(),'hindbærsaft'),
(NEWID(),'hindbærsirup'),
(NEWID(),'hindbærsorbet'),
(NEWID(),'hindbærsyltetøj'),
(NEWID(),'hindbærvineddike'),
(NEWID(),'hirseflage'),
(NEWID(),'hjertebrød'),
(NEWID(),'hjertesalat'),
(NEWID(),'hjortefilet'),
(NEWID(),'hjortetaksalt'),
(NEWID(),'hoisinsauce'),
(NEWID(),'hokkaido græskar'),
(NEWID(),'honning'),
(NEWID(),'honningmelon'),
(NEWID(),'hornfisk'),
(NEWID(),'hovedsalat'),
(NEWID(),'hp sauce'),
(NEWID(),'hummer'),
(NEWID(),'hummerfond'),
(NEWID(),'husblas'),
(NEWID(),'hvedebrød'),
(NEWID(),'hvedekerne'),
(NEWID(),'hvedeklid'),
(NEWID(),'hvedemel'),
(NEWID(),'hvedepandekage'),
(NEWID(),'hvedeøl'),
(NEWID(),'hvid asparges'),
(NEWID(),'hvid balsamicoeddike'),
(NEWID(),'hvid bønne'),
(NEWID(),'hvid peber'),
(NEWID(),'hvidkål'),
(NEWID(),'hvidløg'),
(NEWID(),'hvidløgsolie'),
(NEWID(),'hvidløgspulver'),
(NEWID(),'hvidskimmelost'),
(NEWID(),'hvidtøl'),
(NEWID(),'hvidvin'),
(NEWID(),'hvidvinseddike'),
(NEWID(),'hyben'),
(NEWID(),'hyldeblomsteddike'),
(NEWID(),'hyldeblomstsaft'),
(NEWID(),'hyldeblomstskærm'),
(NEWID(),'hyldebærsaft'),
(NEWID(),'hytteost'),
(NEWID(),'høne'),
(NEWID(),'hønsebouillon'),
(NEWID(),'hønsekødssuppe'),
(NEWID(),'hørfrø'),
(NEWID(),'icebergsalat'),
(NEWID(),'ingefær'),
(NEWID(),'ingefærmarmelade'),
(NEWID(),'isvaffel'),
(NEWID(),'italiensk brød'),
(NEWID(),'italiensk spegepølse'),
(NEWID(),'jalapeno'),
(NEWID(),'jasminris'),
(NEWID(),'jomfruhummerhale'),
(NEWID(),'jomfruolivenolie'),
(NEWID(),'jordbær'),
(NEWID(),'jordbærmarmelade'),
(NEWID(),'jordbærsaft'),
(NEWID(),'jordbærsyltetøj'),
(NEWID(),'jordskok'),
(NEWID(),'julesalat'),
(NEWID(),'kaffe'),
(NEWID(),'kaffebønne'),
(NEWID(),'kaffefløde'),
(NEWID(),'kaffelikør'),
(NEWID(),'kaffepulver'),
(NEWID(),'kakao'),
(NEWID(),'kakaomælk'),
(NEWID(),'kakaopulver'),
(NEWID(),'kakifrugt'),
(NEWID(),'kalamataoliven'),
(NEWID(),'kalkun'),
(NEWID(),'kalkunbacon'),
(NEWID(),'kalkunbryst'),
(NEWID(),'kalkuncuvette'),
(NEWID(),'kalkunschnitzel'),
(NEWID(),'kalkununderlår'),
(NEWID(),'kalv'),
(NEWID(),'kalvebouillon'),
(NEWID(),'kalvebov med ben'),
(NEWID(),'kalvebov uden ben'),
(NEWID(),'kalvebov'),
(NEWID(),'kalvebrissel'),
(NEWID(),'kalveculotte'),
(NEWID(),'kalvecuvette'),
(NEWID(),'kalvefilet'),
(NEWID(),'kalvefond'),
(NEWID(),'kalvehale'),
(NEWID(),'kalveinderlår'),
(NEWID(),'kalvekotelet'),
(NEWID(),'kalvekød'),
(NEWID(),'kalvelever'),
(NEWID(),'kalvemørbrad'),
(NEWID(),'kalveschnitzel'),
(NEWID(),'kalveskank'),
(NEWID(),'kalvespidsbryst'),
(NEWID(),'kalvetykkam'),
(NEWID(),'kalvetyksteg'),
(NEWID(),'kamille'),
(NEWID(),'kamilleblomst'),
(NEWID(),'kammerjunker'),
(NEWID(),'kammusling'),
(NEWID(),'kamut'),
(NEWID(),'kanel'),
(NEWID(),'kanelstang'),
(NEWID(),'kanin'),
(NEWID(),'kaninryg'),
(NEWID(),'kantalupmelon'),
(NEWID(),'kantarel'),
(NEWID(),'kapers'),
(NEWID(),'kapersbær'),
(NEWID(),'kardemomme'),
(NEWID(),'kardemommefrø'),
(NEWID(),'kardemommekapsel'),
(NEWID(),'karry'),
(NEWID(),'karry-ketchup'),
(NEWID(),'karrypasta'),
(NEWID(),'karrysovs'),
(NEWID(),'karrysuppe'),
(NEWID(),'karse'),
(NEWID(),'kartoffel'),
(NEWID(),'kartoffelbåd'),
(NEWID(),'kartoffelmel'),
(NEWID(),'kartoffelmos'),
(NEWID(),'kartoffelsuppe'),
(NEWID(),'kastanjepuré'),
(NEWID(),'kaviar'),
(NEWID(),'kejserhat'),
(NEWID(),'ketchup'),
(NEWID(),'ketjap manis'),
(NEWID(),'kidneybønne'),
(NEWID(),'kiks'),
(NEWID(),'kikært'),
(NEWID(),'kikært i saltlage'),
(NEWID(),'kikærtespire'),
(NEWID(),'kinakål'),
(NEWID(),'kinaradise'),
(NEWID(),'kinareje'),
(NEWID(),'kippers i vand'),
(NEWID(),'kippers'),
(NEWID(),'kirsebær'),
(NEWID(),'kirsebærbrændevin'),
(NEWID(),'kirsebæreddike'),
(NEWID(),'kirsebærlikør'),
(NEWID(),'kirsebærsaft'),
(NEWID(),'kirsebærsauce'),
(NEWID(),'kirsebærvin'),
(NEWID(),'kiwifrugt'),
(NEWID(),'klipfisk'),
(NEWID(),'knoldselleri'),
(NEWID(),'knurhanefilet'),
(NEWID(),'knækbrød'),
(NEWID(),'kogt hamburgerryg'),
(NEWID(),'kogt skinke'),
(NEWID(),'kogt tigerreje'),
(NEWID(),'kokosflage'),
(NEWID(),'kokoslikør'),
(NEWID(),'kokosmel'),
(NEWID(),'kokosmælk'),
(NEWID(),'kokosnød'),
(NEWID(),'kokosolie'),
(NEWID(),'kokossukker'),
(NEWID(),'koldrøget laks'),
(NEWID(),'koldskål'),
(NEWID(),'kommen'),
(NEWID(),'kondenseret mælk'),
(NEWID(),'korender'),
(NEWID(),'koriander'),
(NEWID(),'korianderblade'),
(NEWID(),'korianderfrø'),
(NEWID(),'krabbe'),
(NEWID(),'krabbeklo'),
(NEWID(),'krebs'),
(NEWID(),'krebsehale'),
(NEWID(),'krokodillefilet'),
(NEWID(),'kronhjortemørbrad'),
(NEWID(),'krusemynteblad'),
(NEWID(),'kruspersille'),
(NEWID(),'kryddersmør'),
(NEWID(),'kryddertomat'),
(NEWID(),'krydderurt'),
(NEWID(),'krydret pølse'),
(NEWID(),'krølsalat'),
(NEWID(),'kullerfilet'),
(NEWID(),'kulør'),
(NEWID(),'kumquats'),
(NEWID(),'kvark'),
(NEWID(),'kvæde'),
(NEWID(),'kværnet peber'),
(NEWID(),'kylling'),
(NEWID(),'kyllingebryst'),
(NEWID(),'kyllingefilet'),
(NEWID(),'kyllingefond'),
(NEWID(),'kyllingeinderfilet'),
(NEWID(),'kyllingekød'),
(NEWID(),'kyllingelever'),
(NEWID(),'kyllingelår'),
(NEWID(),'kyllingelårfilet'),
(NEWID(),'kyllingeover- og underlår'),
(NEWID(),'kyllingeoverlår'),
(NEWID(),'kyllingepølse'),
(NEWID(),'kyllingeunderlår'),
(NEWID(),'kålpølse'),
(NEWID(),'kålrabi'),
(NEWID(),'kængurusteak'),
(NEWID(),'kærnemælk'),
(NEWID(),'kødsauce'),
(NEWID(),'kørvel'),
(NEWID(),'kørvelkvist'),
(NEWID(),'lady fingers'),
(NEWID(),'lagereddike'),
(NEWID(),'lagkagebund'),
(NEWID(),'lagkageplast'),
(NEWID(),'lakrids'),
(NEWID(),'lakridspulver'),
(NEWID(),'lakridssirup'),
(NEWID(),'laks'),
(NEWID(),'laksefilet'),
(NEWID(),'laksekotelet'),
(NEWID(),'lakseloin'),
(NEWID(),'lakserogn'),
(NEWID(),'lam'),
(NEWID(),'lammebov'),
(NEWID(),'lammeculotte'),
(NEWID(),'lammefilet'),
(NEWID(),'lammekotelet'),
(NEWID(),'lammekød'),
(NEWID(),'lammekølle'),
(NEWID(),'lammemørbrad'),
(NEWID(),'lammeryg'),
(NEWID(),'lammeschnitzel'),
(NEWID(),'lammeskank'),
(NEWID(),'lammeslag'),
(NEWID(),'lammesmåkød'),
(NEWID(),'lammesteak'),
(NEWID(),'landand'),
(NEWID(),'landbrød'),
(NEWID(),'langefilet'),
(NEWID(),'lasagneplade'),
(NEWID(),'laurbærblad'),
(NEWID(),'lavendel'),
(NEWID(),'lemon curd'),
(NEWID(),'letmælk'),
(NEWID(),'letremoulade'),
(NEWID(),'leverpostej'),
(NEWID(),'likør'),
(NEWID(),'lilla spidskål'),
(NEWID(),'lime usprøjtet'),
(NEWID(),'lime'),
(NEWID(),'limeblad'),
(NEWID(),'limefrugt'),
(NEWID(),'limesaft'),
(NEWID(),'lollo bianco salat'),
(NEWID(),'long bean'),
(NEWID(),'lucernespire'),
(NEWID(),'lufttørret skinke'),
(NEWID(),'lys chokolade'),
(NEWID(),'lys quinoa'),
(NEWID(),'lys rosin'),
(NEWID(),'lys sirup'),
(NEWID(),'lyssejfilet'),
(NEWID(),'lyst brød'),
(NEWID(),'løg'),
(NEWID(),'løgpulver'),
(NEWID(),'løgspire'),
(NEWID(),'løvstikke'),
(NEWID(),'løvstikkeblad'),
(NEWID(),'macademianød'),
(NEWID(),'madlavningsfløde'),
(NEWID(),'madlavningsmælk'),
(NEWID(),'madraskarry'),
(NEWID(),'madæble'),
(NEWID(),'majroe'),
(NEWID(),'majs'),
(NEWID(),'majschips'),
(NEWID(),'majskerne'),
(NEWID(),'majskolbe'),
(NEWID(),'majsmel'),
(NEWID(),'majsstivelse'),
(NEWID(),'makrel i tomat'),
(NEWID(),'makrel'),
(NEWID(),'makrelfilet'),
(NEWID(),'makron'),
(NEWID(),'maltøl'),
(NEWID(),'mandarin'),
(NEWID(),'mandel'),
(NEWID(),'mandelflage'),
(NEWID(),'mandelmel'),
(NEWID(),'mandelsplit'),
(NEWID(),'mandelsmør'),
(NEWID(),'mango'),
(NEWID(),'mangochutney'),
(NEWID(),'marcipan'),
(NEWID(),'marengsbund'),
(NEWID(),'marineret silde'),
(NEWID(),'markchampignon'),
(NEWID(),'marmelade'),
(NEWID(),'mascarpone'),
(NEWID(),'matjessild'),
(NEWID(),'mayonnaise'),
(NEWID(),'medisterpølse'),
(NEWID(),'medium salsa'),
(NEWID(),'mel'),
(NEWID(),'melet kartoffel'),
(NEWID(),'mellemlagret ost med kommen'),
(NEWID(),'mellemlagret ost'),
(NEWID(),'melon'),
(NEWID(),'merian'),
(NEWID(),'merianblad'),
(NEWID(),'meriankvist'),
(NEWID(),'mild mangochutney'),
(NEWID(),'mild ost'),
(NEWID(),'mild sennep'),
(NEWID(),'mildt chilipulver'),
(NEWID(),'miniflute'),
(NEWID(),'minimajs'),
(NEWID(),'minimælk'),
(NEWID(),'minitoast'),
(NEWID(),'miracle whip'),
(NEWID(),'miso'),
(NEWID(),'mizunasalat'),
(NEWID(),'morgenfrueblad'),
(NEWID(),'morkel'),
(NEWID(),'mornaysauce'),
(NEWID(),'morneysauce'),
(NEWID(),'mozzarella'),
(NEWID(),'multefilet'),
(NEWID(),'muscovadosukker'),
(NEWID(),'muskatnød'),
(NEWID(),'musling'),
(NEWID(),'mynte'),
(NEWID(),'mysli'),
(NEWID(),'mælk'),
(NEWID(),'mælkechokolade'),
(NEWID(),'mælkesauce'),
(NEWID(),'mørbrad'),
(NEWID(),'mørk balsamicoeddike'),
(NEWID(),'mørk chokolade'),
(NEWID(),'mørk sirup'),
(NEWID(),'mørk øl'),
(NEWID(),'mørksejfilet'),
(NEWID(),'mørkt rugbrød'),
(NEWID(),'naanbrød'),
(NEWID(),'nakkefilet'),
(NEWID(),'nakkekam'),
(NEWID(),'nakkekotelet'),
(NEWID(),'natron'),
(NEWID(),'nektarin'),
(NEWID(),'nellike'),
(NEWID(),'noritang'),
(NEWID(),'nougat'),
(NEWID(),'nutella'),
(NEWID(),'nøddekurv'),
(NEWID(),'okseben'),
(NEWID(),'oksebouillon'),
(NEWID(),'oksebov'),
(NEWID(),'oksebryst'),
(NEWID(),'oksebøf'),
(NEWID(),'okseculotte'),
(NEWID(),'oksecuvette'),
(NEWID(),'oksefilet'),
(NEWID(),'oksefond'),
(NEWID(),'oksehøjreb'),
(NEWID(),'okseinderlår'),
(NEWID(),'okseklump'),
(NEWID(),'oksekød'),
(NEWID(),'okselårtunge'),
(NEWID(),'oksemørbrad'),
(NEWID(),'oksepølse'),
(NEWID(),'oksesmåkød'),
(NEWID(),'oksespegepølse'),
(NEWID(),'oksetværreb'),
(NEWID(),'oksetykkam'),
(NEWID(),'oksetyndsstegsfilet'),
(NEWID(),'oksetyndsteg'),
(NEWID(),'olie'),
(NEWID(),'oliven'),
(NEWID(),'olivenolie'),
(NEWID(),'oliventapenade'),
(NEWID(),'orange peberfrugt'),
(NEWID(),'orange snackpeber'),
(NEWID(),'orangechokolade'),
(NEWID(),'orangemarmelade'),
(NEWID(),'oregano'),
(NEWID(),'oreganoblade'),
(NEWID(),'ost'),
(NEWID(),'ostesauce'),
(NEWID(),'ostesovs'),
(NEWID(),'ostindisk karry'),
(NEWID(),'overtræksmarcipan'),
(NEWID(),'pak-choi'),
(NEWID(),'palmekålsblad'),
(NEWID(),'pandekage'),
(NEWID(),'pankorasp'),
(NEWID(),'papadum'),
(NEWID(),'papaja'),
(NEWID(),'paprika'),
(NEWID(),'paranøddekerne'),
(NEWID(),'parmaskinke'),
(NEWID(),'parmesan'),
(NEWID(),'passionsfrugt'),
(NEWID(),'pasta'),
(NEWID(),'pastafarve'),
(NEWID(),'pastasauce'),
(NEWID(),'pastaskrue'),
(NEWID(),'pastasovs'),
(NEWID(),'pastinak'),
(NEWID(),'pastrami'),
(NEWID(),'peanutbutter'),
(NEWID(),'peanuts'),
(NEWID(),'peber'),
(NEWID(),'peberfrugt'),
(NEWID(),'peberfrugtpesto'),
(NEWID(),'peberkorn'),
(NEWID(),'pebermynteblad'),
(NEWID(),'pebermyntechokolade'),
(NEWID(),'pebermyntekvist'),
(NEWID(),'pebernød'),
(NEWID(),'peberrod'),
(NEWID(),'pekannød'),
(NEWID(),'pekannøddekerne'),
(NEWID(),'pepperoni'),
(NEWID(),'perlebyg'),
(NEWID(),'perlehønebryst'),
(NEWID(),'perleløg'),
(NEWID(),'perlerug'),
(NEWID(),'perlespelt'),
(NEWID(),'perlesukker'),
(NEWID(),'pernod'),
(NEWID(),'persille'),
(NEWID(),'persillerod'),
(NEWID(),'persillesmør'),
(NEWID(),'pesto'),
(NEWID(),'piccalilly'),
(NEWID(),'pigeonæble'),
(NEWID(),'pighvar'),
(NEWID(),'pillekartoffel'),
(NEWID(),'pilsnerøl'),
(NEWID(),'pinjekerne'),
(NEWID(),'piri piri'),
(NEWID(),'piskefløde'),
(NEWID(),'pistacienød'),
(NEWID(),'pistacienøddeke'),
(NEWID(),'pitabrød'),
(NEWID(),'pizzabund'),
(NEWID(),'pizzadej'),
(NEWID(),'pizzamel'),
(NEWID(),'polenta'),
(NEWID(),'porre'),
(NEWID(),'porresuppe'),
(NEWID(),'porretop'),
(NEWID(),'porter'),
(NEWID(),'portobello'),
(NEWID(),'portvin'),
(NEWID(),'poussin'),
(NEWID(),'pumpernikkel'),
(NEWID(),'purløg'),
(NEWID(),'pære'),
(NEWID(),'pølse'),
(NEWID(),'quinoa'),
(NEWID(),'quinoaflager'),
(NEWID(),'rabarber'),
(NEWID(),'radicchiosalat'),
(NEWID(),'radise'),
(NEWID(),'ramsløg'),
(NEWID(),'rapsolie'),
(NEWID(),'rasp'),
(NEWID(),'ravigottesauce'),
(NEWID(),'ravioli'),
(NEWID(),'regnbueørred'),
(NEWID(),'reje'),
(NEWID(),'remoulade'),
(NEWID(),'revelsben'),
(NEWID(),'revet mozzarella'),
(NEWID(),'revet ost'),
(NEWID(),'ribben svin'),
(NEWID(),'ribbensteg'),
(NEWID(),'ribeye-steak'),
(NEWID(),'ribs'),
(NEWID(),'ribsgelé'),
(NEWID(),'ribssaft'),
(NEWID(),'ris'),
(NEWID(),'risalamande'),
(NEWID(),'riseddike'),
(NEWID(),'risengrød'),
(NEWID(),'rismel'),
(NEWID(),'risnudler'),
(NEWID(),'risottoris'),
(NEWID(),'rispapir'),
(NEWID(),'ristede løg'),
(NEWID(),'risvinseddike'),
(NEWID(),'roastbeef'),
(NEWID(),'rodfrugt'),
(NEWID(),'rodfrugtblanding'),
(NEWID(),'rodfrugtchips'),
(NEWID(),'rom'),
(NEWID(),'romainesalat'),
(NEWID(),'romanescokål'),
(NEWID(),'rosenblad'),
(NEWID(),'rosenkål'),
(NEWID(),'rosenpaprika'),
(NEWID(),'rosin'),
(NEWID(),'rosmarin'),
(NEWID(),'rosmarinblad'),
(NEWID(),'rosmarinkvist'),
(NEWID(),'rucolasalat'),
(NEWID(),'rugbolle'),
(NEWID(),'rugbrød uden kerner'),
(NEWID(),'rugbrød'),
(NEWID(),'rugbrødsbolle'),
(NEWID(),'rugbrødschips'),
(NEWID(),'rugflager'),
(NEWID(),'rugkerne'),
(NEWID(),'rugkiks'),
(NEWID(),'rugmel'),
(NEWID(),'rygeost'),
(NEWID(),'rådyrkølle'),
(NEWID(),'rød chilipeber'),
(NEWID(),'rød grapefrugt'),
(NEWID(),'rød karrypasta'),
(NEWID(),'rød linse'),
(NEWID(),'rød peberfrugt'),
(NEWID(),'rød quinoa'),
(NEWID(),'rød snackpeber'),
(NEWID(),'rød æble'),
(NEWID(),'rødbede'),
(NEWID(),'rødbedeblad'),
(NEWID(),'rødbedesaft'),
(NEWID(),'rødbedespirer'),
(NEWID(),'røde ris'),
(NEWID(),'rødfisk'),
(NEWID(),'rødfiskefilet'),
(NEWID(),'rødkål'),
(NEWID(),'rødløg'),
(NEWID(),'rødløgsmarmelade'),
(NEWID(),'rødskimmel'),
(NEWID(),'rødspætte'),
(NEWID(),'rødspættefilet'),
(NEWID(),'rødtunge'),
(NEWID(),'rødtungefilet'),
(NEWID(),'rødvin'),
(NEWID(),'rødvinseddike'),
(NEWID(),'rødvinssauce'),
(NEWID(),'rødvinssirup'),
(NEWID(),'rødvinssovs'),
(NEWID(),'røget dyrekølle'),
(NEWID(),'røget hellefisk'),
(NEWID(),'røget kalkunbryst'),
(NEWID(),'røget kaviar'),
(NEWID(),'røget kylling'),
(NEWID(),'røget laks'),
(NEWID(),'røget lammekølle'),
(NEWID(),'røget makrel'),
(NEWID(),'røget mandel'),
(NEWID(),'røget musling'),
(NEWID(),'røget paprika'),
(NEWID(),'røget sild'),
(NEWID(),'røget skinke'),
(NEWID(),'røget svinefilet'),
(NEWID(),'røget svinemørbrad'),
(NEWID(),'røget torsk'),
(NEWID(),'røget ørred'),
(NEWID(),'røget ørredfilet'),
(NEWID(),'rørsukker'),
(NEWID(),'rørsukkersirup'),
(NEWID(),'safran'),
(NEWID(),'sake'),
(NEWID(),'salami'),
(NEWID(),'salat'),
(NEWID(),'salatblad'),
(NEWID(),'salatløg'),
(NEWID(),'salatost'),
(NEWID(),'salsa'),
(NEWID(),'salt'),
(NEWID(),'saltet mandel'),
(NEWID(),'saltkiks'),
(NEWID(),'saltlakrids'),
(NEWID(),'salturt'),
(NEWID(),'salvie'),
(NEWID(),'salvieblad'),
(NEWID(),'sambal oelek'),
(NEWID(),'sandart'),
(NEWID(),'sandartfilet med skind'),
(NEWID(),'sandartfilet'),
(NEWID(),'sandwichbolle'),
(NEWID(),'sandwichbrød'),
(NEWID(),'sandwichrugbrød'),
(NEWID(),'sardin'),
(NEWID(),'sauce'),
(NEWID(),'sauterne'),
(NEWID(),'savojkål'),
(NEWID(),'sejfilet'),
(NEWID(),'sellerisalt'),
(NEWID(),'sennep'),
(NEWID(),'sennepsfrø'),
(NEWID(),'sennepskorn'),
(NEWID(),'sennepspickles'),
(NEWID(),'serrano skinke'),
(NEWID(),'sesamfrø'),
(NEWID(),'sesamolie'),
(NEWID(),'sharonfrugt'),
(NEWID(),'sherry'),
(NEWID(),'sherryeddike'),
(NEWID(),'shiitakesvampe'),
(NEWID(),'sigtebrød'),
(NEWID(),'sigtemel'),
(NEWID(),'sild');
GO

INSERT INTO [Ingredient] ([Id],[Name])
VALUES
(NEWID(),'sirup'),
(NEWID(),'skaldyr'),
(NEWID(),'skaldyrsmix'),
(NEWID(),'skalotteløg'),
(NEWID(),'skalreje'),
(NEWID(),'skimmelost'),
(NEWID(),'skinke i tern'),
(NEWID(),'skinke'),
(NEWID(),'skinkeculotte'),
(NEWID(),'skinkeinderlår'),
(NEWID(),'skinkemedaljon'),
(NEWID(),'skinkemignon'),
(NEWID(),'skinkeschnitzel'),
(NEWID(),'skoleagurk'),
(NEWID(),'skorzonerrod'),
(NEWID(),'skovbær'),
(NEWID(),'skovdue'),
(NEWID(),'skovsyre'),
(NEWID(),'skrubbe'),
(NEWID(),'skrubbefilet'),
(NEWID(),'skumfidus'),
(NEWID(),'skummetmælk'),
(NEWID(),'skvalderkål'),
(NEWID(),'skyr'),
(NEWID(),'skårne rugkerner'),
(NEWID(),'skærisingfilet'),
(NEWID(),'slethvar'),
(NEWID(),'slethvarfilet'),
(NEWID(),'slikærter'),
(NEWID(),'smagsneutral olie'),
(NEWID(),'sumak'),
(NEWID(),'smuttet mandel'),
(NEWID(),'smør'),
(NEWID(),'snaps'),
(NEWID(),'soja'),
(NEWID(),'sojasauce'),
(NEWID(),'solbær'),
(NEWID(),'solbærlikør'),
(NEWID(),'solbærmarmelade'),
(NEWID(),'solbærsaft'),
(NEWID(),'solbærsyltetøj'),
(NEWID(),'solsikkekerne'),
(NEWID(),'solsikkeolie'),
(NEWID(),'soltørret abrikos'),
(NEWID(),'soltørret tomat'),
(NEWID(),'sort bønne'),
(NEWID(),'sort kikært'),
(NEWID(),'sort oliven'),
(NEWID(),'sort peber'),
(NEWID(),'sort peberkorn'),
(NEWID(),'sort quinoa'),
(NEWID(),'sorte løgfrø'),
(NEWID(),'sorte ris'),
(NEWID(),'sorte sesamfrø'),
(NEWID(),'spaghetti'),
(NEWID(),'spegepølse'),
(NEWID(),'spegeskinke'),
(NEWID(),'spelt'),
(NEWID(),'speltbrød'),
(NEWID(),'speltflage'),
(NEWID(),'speltkerne'),
(NEWID(),'speltmel'),
(NEWID(),'spidskål'),
(NEWID(),'spinat'),
(NEWID(),'spinatblad'),
(NEWID(),'spisekastanje'),
(NEWID(),'spæk'),
(NEWID(),'squash'),
(NEWID(),'squashblomst'),
(NEWID(),'stegeben'),
(NEWID(),'stegeflæsk'),
(NEWID(),'stenbider'),
(NEWID(),'stenbiderrogn'),
(NEWID(),'stikkelsbær'),
(NEWID(),'stjerneanis'),
(NEWID(),'strudsemedaljon'),
(NEWID(),'stærk chilisauce'),
(NEWID(),'stærk mangochutney'),
(NEWID(),'stærk salsa'),
(NEWID(),'stødt allehånde'),
(NEWID(),'stødt chili'),
(NEWID(),'stødt ingefær'),
(NEWID(),'stødt kardemomme'),
(NEWID(),'stødt koriander'),
(NEWID(),'stødt nellike'),
(NEWID(),'stødt spidskommen'),
(NEWID(),'sugerør'),
(NEWID(),'sukat'),
(NEWID(),'sukker'),
(NEWID(),'sukkerperle'),
(NEWID(),'sukkerært'),
(NEWID(),'sukkerærtespire'),
(NEWID(),'suppe'),
(NEWID(),'suppehøne'),
(NEWID(),'suppeurter'),
(NEWID(),'sur-sød sauce'),
(NEWID(),'surdejsbrød'),
(NEWID(),'surkål'),
(NEWID(),'sushiris'),
(NEWID(),'svampe'),
(NEWID(),'sveske'),
(NEWID(),'svinebov'),
(NEWID(),'svinebryst'),
(NEWID(),'svinefilet'),
(NEWID(),'svinehjerte'),
(NEWID(),'svinekam uden svær'),
(NEWID(),'svinekam'),
(NEWID(),'svinekotelet'),
(NEWID(),'svinekæbe'),
(NEWID(),'svinekød'),
(NEWID(),'svinelever'),
(NEWID(),'svinemørbrad'),
(NEWID(),'svinenakkefilet'),
(NEWID(),'svineskank'),
(NEWID(),'svineslag'),
(NEWID(),'syltede rødløg'),
(NEWID(),'syltet abrikos'),
(NEWID(),'syltet agurk'),
(NEWID(),'syltet figen'),
(NEWID(),'syltet ingefær'),
(NEWID(),'syltet kirsebær'),
(NEWID(),'syltet peberfrugt'),
(NEWID(),'syltet perleløg'),
(NEWID(),'syltet pære'),
(NEWID(),'syltet rødbede'),
(NEWID(),'syltetøj'),
(NEWID(),'sød chilisauce'),
(NEWID(),'sød hvidvin'),
(NEWID(),'sød kartoffel'),
(NEWID(),'sød tranebærsaft'),
(NEWID(),'sødmælk'),
(NEWID(),'sødmælksyoghurt'),
(NEWID(),'sølvbede'),
(NEWID(),'søtungefilet'),
(NEWID(),'t-bonesteak'),
(NEWID(),'tabascosauce'),
(NEWID(),'tacokrydderi'),
(NEWID(),'tacosauce'),
(NEWID(),'tacoskal'),
(NEWID(),'taffelsennep'),
(NEWID(),'tahin'),
(NEWID(),'tamarind'),
(NEWID(),'tamarindpasta'),
(NEWID(),'tandoori'),
(NEWID(),'tandoorikrydderi'),
(NEWID(),'tandooripasta'),
(NEWID(),'tang'),
(NEWID(),'tartelet'),
(NEWID(),'teriyakisauce'),
(NEWID(),'thai chilisauce'),
(NEWID(),'thaisuppe'),
(NEWID(),'tigerreje'),
(NEWID(),'tikka masala'),
(NEWID(),'timian'),
(NEWID(),'timianblade'),
(NEWID(),'toastbrød'),
(NEWID(),'tomat'),
(NEWID(),'tomatchutney'),
(NEWID(),'tomatjuice'),
(NEWID(),'tomatketchup'),
(NEWID(),'tomatpesto'),
(NEWID(),'tomatpuré'),
(NEWID(),'tomatrelish'),
(NEWID(),'tomatsalat'),
(NEWID(),'tomatsalsa'),
(NEWID(),'tomatsauce'),
(NEWID(),'tomatsuppe'),
(NEWID(),'torsk'),
(NEWID(),'torskefilet'),
(NEWID(),'torskerogn'),
(NEWID(),'tortellini'),
(NEWID(),'tortilla'),
(NEWID(),'tortillachips'),
(NEWID(),'tranebær'),
(NEWID(),'tranebærgelé'),
(NEWID(),'tranebærsyltetøj'),
(NEWID(),'tropejuice'),
(NEWID(),'trøffel'),
(NEWID(),'trøffelolie'),
(NEWID(),'tun i olie'),
(NEWID(),'tun i tomat'),
(NEWID(),'tun i vand'),
(NEWID(),'tun'),
(NEWID(),'tusindfryd'),
(NEWID(),'tvebak'),
(NEWID(),'tykmælk'),
(NEWID(),'tyrkisk brød'),
(NEWID(),'tyttebær'),
(NEWID(),'tyttebærsyltetøj'),
(NEWID(),'tærtedej'),
(NEWID(),'tør hvidvin'),
(NEWID(),'tør sherry'),
(NEWID(),'tørgær'),
(NEWID(),'tørrede ægnudler'),
(NEWID(),'tørret abrikos'),
(NEWID(),'tørret basilikum'),
(NEWID(),'tørret blåbær'),
(NEWID(),'tørret daddel'),
(NEWID(),'tørret estragon'),
(NEWID(),'tørret figen'),
(NEWID(),'tørret kantarel'),
(NEWID(),'tørret kikært'),
(NEWID(),'tørret limeblad'),
(NEWID(),'tørret oregano'),
(NEWID(),'tørret pebermynte'),
(NEWID(),'tørret rosmarin'),
(NEWID(),'tørret svamp'),
(NEWID(),'tørret tranebær'),
(NEWID(),'ufarvet kaviar'),
(NEWID(),'unghane'),
(NEWID(),'unghanebryst'),
(NEWID(),'usaltet peanut'),
(NEWID(),'usaltet pistacienøddekerne'),
(NEWID(),'vagtel'),
(NEWID(),'vagtelæg'),
(NEWID(),'valnød'),
(NEWID(),'valnøddekerne'),
(NEWID(),'valnøddeolie'),
(NEWID(),'vand'),
(NEWID(),'vandkastanje'),
(NEWID(),'vandmelon'),
(NEWID(),'Vanilje'),
(NEWID(),'vaniljeekstrakt'),
(NEWID(),'vaniljeflødeis'),
(NEWID(),'vaniljekiks'),
(NEWID(),'vaniljepulver'),
(NEWID(),'vaniljesauce'),
(NEWID(),'vaniljestang'),
(NEWID(),'vaniljesukker'),
(NEWID(),'varmrøget laks'),
(NEWID(),'vejbred'),
(NEWID(),'victoriafisk'),
(NEWID(),'vilde ris'),
(NEWID(),'vildsvin'),
(NEWID(),'vildtbouillon'),
(NEWID(),'vindrue'),
(NEWID(),'vineddike'),
(NEWID(),'vinrabarber'),
(NEWID(),'vintersar'),
(NEWID(),'vintersarblad'),
(NEWID(),'viol'),
(NEWID(),'wakame tang'),
(NEWID(),'wasabi'),
(NEWID(),'whisky'),
(NEWID(),'whiskylikør'),
(NEWID(),'whiskysauce'),
(NEWID(),'wienerpølse'),
(NEWID(),'wontondej'),
(NEWID(),'worcestershiresauce'),
(NEWID(),'ymer'),
(NEWID(),'yoghurt'),
(NEWID(),'zittauerløg'),
(NEWID(),'æble'),
(NEWID(),'æblecider'),
(NEWID(),'æblecidereddike'),
(NEWID(),'æbleeddike'),
(NEWID(),'æblegelé'),
(NEWID(),'æblejuice'),
(NEWID(),'æblemost'),
(NEWID(),'æblesirup'),
(NEWID(),'æbleskiver'),
(NEWID(),'æblevineddike'),
(NEWID(),'æg'),
(NEWID(),'æggeblomme'),
(NEWID(),'æggehvide'),
(NEWID(),'ægnudler'),
(NEWID(),'ærter'),
(NEWID(),'ærteskud'),
(NEWID(),'øl'),
(NEWID(),'ørred'),
(NEWID(),'ørredfilet'),
(NEWID(),'ørredrogn'),
(NEWID(),'østers'),
(NEWID(),'østershatte'),
(NEWID(),'østerssauce');
GO